config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :passwords     => 'users/passwords',
    :sessions      => 'users/sessions'
  }
  devise_scope :user do
    get "sign_in",  :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end
  resources :users
  resources :restaurants do
    resources :schedules, only: [:new, :create, :edit, :update]
  end

  get 'record' => 'record#index'


  root 'restaurants#index'
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :restaurant, foreign_key: 'restaurant_id'
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:edit, :update]
  before_action :authenticate_user!


  def index
    @schedules = Schedule.all
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @schedule   = Schedule.new
  end


  def edit
  end


  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      redirect_to root_path, notice: 'Schedule was successfully created.'
    else
      render :new
    end
  end


  def update
      if @schedule.update(schedule_params)
        redirect_to root_path, notice: 'Schedule was successfully updated.'
      else
        render :edit
      end
  end


  private
    def set_schedule
      @restaurant = Restaurant.find(params[:restaurant_id])
      @schedule   = Schedule.find(params[:id])
    end


    def schedule_params
      params.require(:schedule).permit(:restaurant_id, :time0000, :time0015, :time0030, :time0045, :time0100, :time0115, :time0130, :time0145, :time0200, :time0215, :time0230, :time0245, :time0300, :time0315, :time0330, :time0345, :time0400, :time0415, :time0430, :time0445, :time0500, :time0515, :time0530, :time0545, :time0600, :time0615, :time0630, :time0645, :time0700, :time0715, :time0730, :time0745, :time0800, :time0815, :time0830, :time0845, :time0900, :time0915, :time0930, :time0945, :time1000, :time1015, :time1030, :time1045, :time1100, :time1115, :time1130, :time1145, :time1200, :time1215, :time1230, :time1245, :time1300, :time1315, :time1330, :time1345, :time1400, :time1415, :time1430, :time1445, :time1500, :time1515, :time1530, :time1545, :time1600, :time1615, :time1630, :time1645, :time1700, :time1715, :time1730, :time1745, :time1800, :time1815, :time1830, :time1845, :time1900, :time1915, :time1930, :time1945, :time2000, :time2015, :time2030, :time2045, :time2100, :time2115, :time2130, :time2145, :time2200, :time2215, :time2230, :time2245, :time2300, :time2315, :time2330, :time2345)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/edit.html.slim
section.content-header
  h1 Editing schedule

section.content
  == render 'form'

app/views/schedules/index.html.slim
h1 Listing schedules

table
  thead
    tr
      th Restaurant
      th Time0000
      th Time0015
      th Time0030
      th Time0045
      th Time0100
      th Time0115
      th Time0130
      th Time0145
      th Time0200
      th Time0215
      th Time0230
      th Time0245
      th Time0300
      th Time0315
      th Time0330
      th Time0345
      th Time0400
      th Time0415
      th Time0430
      th Time0445
      th Time0500
      th Time0515
      th Time0530
      th Time0545
      th Time0600
      th Time0615
      th Time0630
      th Time0645
      th Time0700
      th Time0715
      th Time0730
      th Time0745
      th Time0800
      th Time0815
      th Time0830
      th Time0845
      th Time0900
      th Time0915
      th Time0930
      th Time0945
      th Time1000
      th Time1015
      th Time1030
      th Time1045
      th Time1100
      th Time1115
      th Time1130
      th Time1145
      th Time1200
      th Time1215
      th Time1230
      th Time1245
      th Time1300
      th Time1315
      th Time1330
      th Time1345
      th Time1400
      th Time1415
      th Time1430
      th Time1445
      th Time1500
      th Time1515
      th Time1530
      th Time1545
      th Time1600
      th Time1615
      th Time1630
      th Time1645
      th Time1700
      th Time1715
      th Time1730
      th Time1745
      th Time1800
      th Time1815
      th Time1830
      th Time1845
      th Time1900
      th Time1915
      th Time1930
      th Time1945
      th Time2000
      th Time2015
      th Time2030
      th Time2045
      th Time2100
      th Time2115
      th Time2130
      th Time2145
      th Time2200
      th Time2215
      th Time2230
      th Time2245
      th Time2300
      th Time2315
      th Time2330
      th Time2345
      th
      th
      th

  tbody
    - @schedules.each do |schedule|
      tr
        td = schedule.restaurant_id
        td = schedule.time0000
        td = schedule.time0015
        td = schedule.time0030
        td = schedule.time0045
        td = schedule.time0100
        td = schedule.time0115
        td = schedule.time0130
        td = schedule.time0145
        td = schedule.time0200
        td = schedule.time0215
        td = schedule.time0230
        td = schedule.time0245
        td = schedule.time0300
        td = schedule.time0315
        td = schedule.time0330
        td = schedule.time0345
        td = schedule.time0400
        td = schedule.time0415
        td = schedule.time0430
        td = schedule.time0445
        td = schedule.time0500
        td = schedule.time0515
        td = schedule.time0530
        td = schedule.time0545
        td = schedule.time0600
        td = schedule.time0615
        td = schedule.time0630
        td = schedule.time0645
        td = schedule.time0700
        td = schedule.time0715
        td = schedule.time0730
        td = schedule.time0745
        td = schedule.time0800
        td = schedule.time0815
        td = schedule.time0830
        td = schedule.time0845
        td = schedule.time0900
        td = schedule.time0915
        td = schedule.time0930
        td = schedule.time0945
        td = schedule.time1000
        td = schedule.time1015
        td = schedule.time1030
        td = schedule.time1045
        td = schedule.time1100
        td = schedule.time1115
        td = schedule.time1130
        td = schedule.time1145
        td = schedule.time1200
        td = schedule.time1215
        td = schedule.time1230
        td = schedule.time1245
        td = schedule.time1300
        td = schedule.time1315
        td = schedule.time1330
        td = schedule.time1345
        td = schedule.time1400
        td = schedule.time1415
        td = schedule.time1430
        td = schedule.time1445
        td = schedule.time1500
        td = schedule.time1515
        td = schedule.time1530
        td = schedule.time1545
        td = schedule.time1600
        td = schedule.time1615
        td = schedule.time1630
        td = schedule.time1645
        td = schedule.time1700
        td = schedule.time1715
        td = schedule.time1730
        td = schedule.time1745
        td = schedule.time1800
        td = schedule.time1815
        td = schedule.time1830
        td = schedule.time1845
        td = schedule.time1900
        td = schedule.time1915
        td = schedule.time1930
        td = schedule.time1945
        td = schedule.time2000
        td = schedule.time2015
        td = schedule.time2030
        td = schedule.time2045
        td = schedule.time2100
        td = schedule.time2115
        td = schedule.time2130
        td = schedule.time2145
        td = schedule.time2200
        td = schedule.time2215
        td = schedule.time2230
        td = schedule.time2245
        td = schedule.time2300
        td = schedule.time2315
        td = schedule.time2330
        td = schedule.time2345
        td = link_to 'Show', schedule
        td = link_to 'Edit', edit_schedule_path(schedule)
        td = link_to 'Destroy', schedule, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Schedule', new_schedule_path

app/views/schedules/new.html.slim
h1 New schedule

== render 'form'

= link_to 'Back', :back

app/views/schedules/show.html.slim
p#notice = notice

p
  strong Restaurant:
  = @schedule.restaurant_id
p
  strong Time0000:
  = @schedule.time0000
p
  strong Time0015:
  = @schedule.time0015
p
  strong Time0030:
  = @schedule.time0030
p
  strong Time0045:
  = @schedule.time0045
p
  strong Time0100:
  = @schedule.time0100
p
  strong Time0115:
  = @schedule.time0115
p
  strong Time0130:
  = @schedule.time0130
p
  strong Time0145:
  = @schedule.time0145
p
  strong Time0200:
  = @schedule.time0200
p
  strong Time0215:
  = @schedule.time0215
p
  strong Time0230:
  = @schedule.time0230
p
  strong Time0245:
  = @schedule.time0245
p
  strong Time0300:
  = @schedule.time0300
p
  strong Time0315:
  = @schedule.time0315
p
  strong Time0330:
  = @schedule.time0330
p
  strong Time0345:
  = @schedule.time0345
p
  strong Time0400:
  = @schedule.time0400
p
  strong Time0415:
  = @schedule.time0415
p
  strong Time0430:
  = @schedule.time0430
p
  strong Time0445:
  = @schedule.time0445
p
  strong Time0500:
  = @schedule.time0500
p
  strong Time0515:
  = @schedule.time0515
p
  strong Time0530:
  = @schedule.time0530
p
  strong Time0545:
  = @schedule.time0545
p
  strong Time0600:
  = @schedule.time0600
p
  strong Time0615:
  = @schedule.time0615
p
  strong Time0630:
  = @schedule.time0630
p
  strong Time0645:
  = @schedule.time0645
p
  strong Time0700:
  = @schedule.time0700
p
  strong Time0715:
  = @schedule.time0715
p
  strong Time0730:
  = @schedule.time0730
p
  strong Time0745:
  = @schedule.time0745
p
  strong Time0800:
  = @schedule.time0800
p
  strong Time0815:
  = @schedule.time0815
p
  strong Time0830:
  = @schedule.time0830
p
  strong Time0845:
  = @schedule.time0845
p
  strong Time0900:
  = @schedule.time0900
p
  strong Time0915:
  = @schedule.time0915
p
  strong Time0930:
  = @schedule.time0930
p
  strong Time0945:
  = @schedule.time0945
p
  strong Time1000:
  = @schedule.time1000
p
  strong Time1015:
  = @schedule.time1015
p
  strong Time1030:
  = @schedule.time1030
p
  strong Time1045:
  = @schedule.time1045
p
  strong Time1100:
  = @schedule.time1100
p
  strong Time1115:
  = @schedule.time1115
p
  strong Time1130:
  = @schedule.time1130
p
  strong Time1145:
  = @schedule.time1145
p
  strong Time1200:
  = @schedule.time1200
p
  strong Time1215:
  = @schedule.time1215
p
  strong Time1230:
  = @schedule.time1230
p
  strong Time1245:
  = @schedule.time1245
p
  strong Time1300:
  = @schedule.time1300
p
  strong Time1315:
  = @schedule.time1315
p
  strong Time1330:
  = @schedule.time1330
p
  strong Time1345:
  = @schedule.time1345
p
  strong Time1400:
  = @schedule.time1400
p
  strong Time1415:
  = @schedule.time1415
p
  strong Time1430:
  = @schedule.time1430
p
  strong Time1445:
  = @schedule.time1445
p
  strong Time1500:
  = @schedule.time1500
p
  strong Time1515:
  = @schedule.time1515
p
  strong Time1530:
  = @schedule.time1530
p
  strong Time1545:
  = @schedule.time1545
p
  strong Time1600:
  = @schedule.time1600
p
  strong Time1615:
  = @schedule.time1615
p
  strong Time1630:
  = @schedule.time1630
p
  strong Time1645:
  = @schedule.time1645
p
  strong Time1700:
  = @schedule.time1700
p
  strong Time1715:
  = @schedule.time1715
p
  strong Time1730:
  = @schedule.time1730
p
  strong Time1745:
  = @schedule.time1745
p
  strong Time1800:
  = @schedule.time1800
p
  strong Time1815:
  = @schedule.time1815
p
  strong Time1830:
  = @schedule.time1830
p
  strong Time1845:
  = @schedule.time1845
p
  strong Time1900:
  = @schedule.time1900
p
  strong Time1915:
  = @schedule.time1915
p
  strong Time1930:
  = @schedule.time1930
p
  strong Time1945:
  = @schedule.time1945
p
  strong Time2000:
  = @schedule.time2000
p
  strong Time2015:
  = @schedule.time2015
p
  strong Time2030:
  = @schedule.time2030
p
  strong Time2045:
  = @schedule.time2045
p
  strong Time2100:
  = @schedule.time2100
p
  strong Time2115:
  = @schedule.time2115
p
  strong Time2130:
  = @schedule.time2130
p
  strong Time2145:
  = @schedule.time2145
p
  strong Time2200:
  = @schedule.time2200
p
  strong Time2215:
  = @schedule.time2215
p
  strong Time2230:
  = @schedule.time2230
p
  strong Time2245:
  = @schedule.time2245
p
  strong Time2300:
  = @schedule.time2300
p
  strong Time2315:
  = @schedule.time2315
p
  strong Time2330:
  = @schedule.time2330
p
  strong Time2345:
  = @schedule.time2345

= link_to 'Edit', edit_schedule_path(@schedule)
'|
= link_to 'Back', schedules_path