config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :passwords     => 'users/passwords',
    :sessions      => 'users/sessions'
  }
  devise_scope :user do
    get "sign_in",  :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end
  resources :users
  resources :restaurants do
    resources :schedules, only: [:new, :create, :edit, :update]
  end

  get 'record' => 'record#index'


  root 'restaurants#index'
end

app/views/layouts/_footer.html.slim
- if user_signed_in?
  footer.main-footer
    .pull-right.hidden-xs
      b Let's Update Everytime
    strong
      | Copyright &copy; 2016

app/views/layouts/_navigation.html.slim
aside.main-sidebar.text-white
  /! sidebar: style can be found in sidebar.less
  section.sidebar
    /! sidebar menu: : style can be found in sidebar.less
    ul.sidebar-menu
      - if user_signed_in?
        li.header
          | − MAIN NAVIGATION −
        li
          = link_to 'Home', root_path
        li
          = link_to 'Create Restaurant', new_restaurant_path
        li
          = link_to 'Records', record_path

app/views/layouts/_topnavbar.html.slim
header.main-header.text-white
  /! Logo
  = link_to 'Auto Update', root_path ,class: 'logo'
  /! Header Navbar: style can be found in header.less
  nav.navbar.navbar-static-top role="navigation"
    .navbar-custom-menu
      ul.nav.navbar-nav
        li.dropdown.user.user-menu
          - if user_signed_in?
            = link_to "Logout", destroy_user_session_path, method: :delete

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    title ぐる自動更新
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  body#bubbles.animated.fadeInRight
    / Wrapper
    .wrapper.text-white
      = render 'layouts/topnavbar'
      = render 'layouts/navigation'
      / Page wrapper
      .content-wrapper.text-white
        / Main view
        = yield
      / Footer
      = render 'layouts/footer'